server:
  port: 5000
spring:
  cloud:
    gateway:
      routes:
        - id: oss
          uri: lb://cqupt-hub-oss
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
        - id: cqupt-hub-auth
          uri: lb://cqupt-hub-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: cqupt-hub-subject
          uri: lb://cqupt-hub-subject
          predicates:
            - Path=/subject/**
          filters:
            - StripPrefix=1